### ISSUE TITLE
oxi_peaks issues

### ISSUE THREAD

**Issue by GidLev** [embodied-computation-group/systole#11]
Hi,

I have been using the Systole package recently and it is a great tool!

Two minor suggestion regarding the oxi_peaks function:
peak_enhancement  -
```
    if peak_enhancement is True:
        # Square signal (peak enhancement)
        x = np.asarray(x) ** 2
```
By raising the signal to the power of 2, negative values turn to positive values causing negative peaks in the data to be detected. I recommend multiplying by the sign of the data:
```
    if peak_enhancement is True:
        # Square signal (peak enhancement)
        x = (np.asarray(x) ** 2) * np.sign(x)
```

rollingNoise - A second issue the window size of the rolling mean. When the sampling rate is too low (10Hz for example) ```int(sfreq * 0.05) ``` is zero, causing the function to return all nans. I recommended changing to:

```
rollingNoise = max(int(sfreq * 0.05), 1)  # 0.05 second window
```
This would make sure that the window size is at least 1.

I can make a pull request with both changes if you want.

**Comment by LegrandNico** [comment]
Hi @GidLev ,

Thank you for opening this issue and your interest in our package.

The `oxi_peaks` function is indeed currently a very simple approach to systolic peak detection that has been working very well with the ppg signal we have been analyzing so far (reasonably good quality, only positive values, and sampling rate > 75Hz). So the changes you are proposing make sense for me and would make this function more generalizable to other signals.

You can create a pull request on the dev branch if you want, this function has been renamed `ppg_peaks` for consistency. I will try to release v0.2.0 later this month.

Thank you for your help with Systole!
