### ISSUE TITLE
Get the beat to beat (RR) time series

### ISSUE THREAD

**Issue by GidLev** [embodied-computation-group/systole#13]
Hi,

I thought it could be useful if the "to_rr" function could return a time series instead of a list of intervals. 
I have made the following changes to the function:

```
def to_rr(peaks: Union[List[float], np.ndarray], sfreq: int = 1000, time_s: bool = False) -> np.ndarray:
    """Convert peaks index to intervals time series (RR, beat-to-beat...).
    Parameters
    ----------
    peaks : np.ndarray or list
        Either a boolean array or sample index. Default is *boolean*. If the
        input array does not only contain 0 or 1, will automatically try sample
        index.
    sfreq : int
        The sampling frequency (default is 1000 Hz).
    time_s: bool
        Whether to return an RR time series in that contains the distance to
        the next beat in each time point.
    Returns
    -------
    rr : np.ndarray
        Interval time series (in miliseconds).
    """
    if isinstance(peaks, list):
        peaks = np.asarray(peaks)
    if ((peaks == 1) | (peaks == 0)).all():
        rr = (np.diff(np.where(peaks)[0]) / sfreq) * 1000
    else:
        rr = (np.diff(peaks) / sfreq) * 1000
    if time_s:
        if ((peaks == 1) | (peaks == 0)).all():
            rr_time_series = np.zeros_like(peaks, dtype=float)
            non_zero_inds = np.where(peaks)[0]
            rr_time_series[non_zero_inds[:-1]] = rr
            # now replace zeros with last non-zero value
            last_non_zero = np.arange(len(rr_time_series))
            last_non_zero[rr_time_series == 0] = 0
            last_non_zero = np.maximum.accumulate(last_non_zero)
            rr_time_series = rr_time_series[last_non_zero]
            rr_time_series[:non_zero_inds[0]] = rr[0] # fill the first zero elements
            return rr_time_series
        else:
            raise ValueError('To get a RR time peaks must be a boolean array.')
    else:
        return rr

```
let me know if you want me to prepare a pulll request with this change.

Best,
Gidon

**Comment by LegrandNico** [comment]
Hi Gibon,

So I have already largely rewritten this function in preparation for the next release (0.2.0) that will integrate several changes in Systole, especially in terms of code optimization and plotting functions. I recommend that you check the dev branch, the new function is now [input_conversion()](https://github.com/embodied-computation-group/systole/blob/55f47690f99cb2d4c11c4ac95db37909ac9ab5de/systole/utils.py#L469), and it is used to convert between several encoding we can have in Systole (boolean peaks vector, peaks index, RR intervals in seconds or milliseconds). This function can now take any of these inputs and convert them to any other format, it is used as the first step of many functions to give flexibility in terms of possible input format for the user.

I think the change you propose is already covered by the [heart_rate()](https://github.com/embodied-computation-group/systole/blob/55f47690f99cb2d4c11c4ac95db37909ac9ab5de/systole/utils.py#L90) function, that interpolate the RR intervals into a continuous time series.

Let me know if my comments make sense. I am working on the tutorial notebooks that will explain all this detail so the documentation should be more clear in the future ;)

Best

**Comment by GidLev** [comment]
Hi Nicolas,

Thanks for your answer, it seems that the functions you describe provide a solution for the problem.

Best,
Gidon
