### ISSUE TITLE
Error in correction.py

### ISSUE THREAD

**Issue by peter-doggart** [embodied-computation-group/systole#14]
Working on a Julia implementation of the reference paper used and noticed variation in results against your library. I narrowed it down to what I think is an error in `correction.py`. Current source reads:
```python
    # Correct extra beats
    if extra_correction:
        if np.any(artefacts["extra"]):
            for this_id in np.where(artefacts["extra"])[0]:
                this_id -= nExtra
                clean_rr = correct_missed(clean_rr, this_id) # This is the incorrect function call.
                nExtra += 1
        artefacts = rr_artefacts(clean_rr)
```

Should read:
```python
    # Correct extra beats
    if extra_correction:
        if np.any(artefacts["extra"]):
            for this_id in np.where(artefacts["extra"])[0]:
                this_id -= nExtra
                clean_rr = correct_extra(clean_rr, this_id) # Should be a call to correct_extra instead.
                nExtra += 1
        artefacts = rr_artefacts(clean_rr)
```
I can probably generate a PR to fix this if you allow contributions?

**Comment by LegrandNico** [comment]
Hi @peter-doggart ,

Yes, nice catch indeed, you can make a pull request on the dev branch and add your name to the list of contributors if you want.

I am curious to see how it goes for your Julia implementation, are you working on the Lipponen & Tarvainen (2019) paper? I am sometimes a bit confused by the way it detects artefacts, I think I should implement more rigorous testing against the same database they are using in the paper.

Thank you for your help,

**Comment by peter-doggart** [comment]
Hi @LegrandNico , 

I have added a Pull Request to fix this issue. :smile: 

Yes, I am working on the Lipponen & Tarvainen (2019) paper. I have built all of it into Julia this week, I plan on getting some time towards the end of this week / next weekend to try and recreate the results in the paper - so I will let you know how it goes! 

Pete
