### ISSUE TITLE
Reference not showing up properly

### ISSUE THREAD

**Issue by osorensen** [embodied-computation-group/systole#30]
On line 46, a reference shows up as "`@lipponen:2019`". Please make sure this is corrected.

https://github.com/openjournals/joss-reviews/issues/3832

**Comment by LegrandNico** [comment]
I have some difficulties understanding what is going on here, as from what I can see in [the JOSS documentation](https://joss.readthedocs.io/en/latest/submitting.html) the citation conforms to the syntax:

```
For a quick reference, the following citation commands can be used:
- `@author:2001`  ->  "Author et al. (2001)"
- `[@author:2001]` -> "(Author et al., 2001)"
- `[@author1:2001; @author2:2001]` -> "(Author1 et al., 2001; Author2 et al., 2002)"
```

**Comment by osorensen** [comment]
Agree that it's confusing, but the outer quotation marks should not be included. I checked that it compiles properly with this fixed, and created a PR.
