### ISSUE TITLE
Wrong module reference in the example

### ISSUE THREAD

**Issue by htwangtw** [embodied-computation-group/systole#4]
Thanks for creating this project. I found a minor error in the example/readme file
In the HRV section
```
from systole.hrv import plot_psd
```
should be
```
from systole.plotting import plot_psd
```
I am not sure if this is the only place the error occurs. 

Thanks!

**Comment by LegrandNico** [comment]
Thank you for reporting this error. It is now corrected, you will see the change in v. 0.1.1 we are about to release.
