### ISSUE TITLE
RR correction order causes index overflows

### ISSUE THREAD

**Issue by Tommilala** [embodied-computation-group/systole#40]
The function `correction.correct_rr()` first corrects artefacts labelled as missed or extra which change the number of RR intervals. This can cause the artefact corrections for the remaining types to fail in `interpolate_bads()` when `idx` can exceed `len(rr)`, causing `interp1d()` to raise an exception. The reason for this is that `interpolate_bads()` is fed with `cleaned_rr` which may or may not correspond in length to the original `rr` for which the artefact detection was done. 

I might make a pull request later. A quick solution is to change the order of the corrections, such that the corrections using interpolation come first. 

Another question that might not be worth of an own issue, why is `rr_artefacts(clean_rr)` called iteratively after each correction bracket? I don't think that is the point in the original paper, as the committed corrections to `clean_rr` will affect the remaining detections, as the rolling thresholds are changed. The correction type annotations and the number of corrections will obviously differ running the artefact detection and the correction routine. Removing these and relying on the single pass artefact detection could cause inconsistent indexing for the short and long corrections, as they are done sequentially.

**Comment by LegrandNico** [comment]
Hi @Tommilala , thank you for pointing to this.

Yes, this function needs some corrections, and more generally I would like to extend it to different methods for correction in the RR domain (if you know some alternatives feel free to cite some here). The idea of the current implementation is that one iteration would be equivalent (as close as we could get so far) to the method described in the paper. The idea of the many iteration approaches is that the threshold can be more reliable once some of the extreme short and long artefacts are removed, but I agree this should be made more apparent to the user.

You can make a PR if you have time and I can work from it. I will be travelling to Helsinki for ICON next week but will have a look when I have time.

**Comment by Tommilala** [comment]
Hey @LegrandNico and thanks for the answer. 

To be more precise on the second point, following the original paper, I don't see why `artefacts = rr_artefacts(clean_rr)` is reassigned on lines 197, 212, 226, 240 and 254, in between the corrections. Extreme errors in the data are not corrected with a single pass but shouldn't the many iteration approach be affected only by the parameter `n_iterations`? Each pass currently runs the detection a total of 6 times. Think of artefacts labelled as extra on the first pass on line 171. The function first replaces artefacts labelled as missed, after which the update on line 197 results in potentially different extra beats to be corrected in the following bracket. My point being, the detection passes during the loop are not following the original paper to my knowledge and potentially lose information during the correction pass.

The effect of this is that visibly false positive corrections end up in the corrected data and it is difficult to follow up on what basis a given point was altered.  Surely, this results in a smoother RR series and HRV measures for sure, but whether it is justified and results in better representation of the normal sinus rhythm is another question. 

The actual bug is less apparent with these re-detections of artects between the passes, as the the returned indices are at least closer to the length of the current RR series being updated. Now that I think of it, it might also be the case that in my suggestion the corrections should be done independently of the collector `clean_rr`. I'll try to push myself into submitting a PR.

**Comment by LegrandNico** [comment]
The errors mentioned should have been fixed in the previous commits and the function now match exactly the method proposed in the original paper, I will close here but feel free to reopen if something is not working.
