### ISSUE TITLE
I want to use this package with emotibit.

### ISSUE THREAD

**Issue by npdrbong** [embodied-computation-group/systole#47]
Hello, thank you for make this wonderful package for cardioception researches.

In our laboratory, we have emotibit device and want to adjust this package with emotibit device.

For this, what procedure or classes need to be update?

Thank you for reading!

**Comment by LegrandNico** [comment]
Hi @npdrbong , thank you for reaching out,

So it depends on whether you want to record or analyse the PPG signal. 

If you're going to analyse it you can pass your signal as Numpy/Pandas time series to any function in the package. 

If you want to read the PPG signal from your device you probably want to write a new class similar to [Oximeter](https://github.com/embodied-computation-group/systole/blob/9351167bf5704ee94c899fef78412253b7b95bb7/systole/recording.py#L15) that will read new packets as they come in, see especially [this part](https://github.com/embodied-computation-group/systole/blob/9351167bf5704ee94c899fef78412253b7b95bb7/systole/recording.py#L189). Nonin pulse oximeter interface via USB, so we use PySerial here, but this is maybe different for your device.

If you have something working following that template this is something that can be contributed to the recording module, the library is intended to work with different devices but I only have access to a limited range of models :blush:.

**Comment by npdrbong** [comment]
Thanks a lot!
